server:
  port: 8081

# 分组任务配置
chatbot-api:
  launchList: group01 # 启动几组，就配置几组
  group01:
    groupName: ChatGPT AI 问答助手
    groupId:  48888125158188 # 知识星球ID
    cookie: zsxq_access_token=B7378E4C-6177-EA28-FFA3-49847768420C_88C8C9B07BCB99FD; zsxqsessionid=e0b2e677335f1f5aae9357ddcb84c36e; abtest_env=product; sajssdk_2015_cross_new_user=1; sensorsdata2015jssdkcross=%7B%22distinct_id%22%3A%22415454814188548%22%2C%22first_id%22%3A%2219486e59a83aec-031dc7645cfd1ee-4c657b58-2073600-19486e59a84f1c%22%2C%22props%22%3A%7B%7D%2C%22identities%22%3A%22eyIkaWRlbnRpdHlfY29va2llX2lkIjoiMTk0ODZlNTlhODNhZWMtMDMxZGM3NjQ1Y2ZkMWVlLTRjNjU3YjU4LTIwNzM2MDAtMTk0ODZlNTlhODRmMWMiLCIkaWRlbnRpdHlfbG9naW5faWQiOiI0MTU0NTQ4MTQxODg1NDgifQ%3D%3D%22%2C%22history_login_id%22%3A%7B%22name%22%3A%22%24identity_login_id%22%2C%22value%22%3A%22415454814188548%22%7D%
    openAiKey: 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 # 自行申请 https://beta.openai.com/overview
    cronExpression: MC8zMCAqICogKiAqID8=  # 执行的频次配置，参考：cron.qqe2.com
    silenced: false
  group02:
    groupName: test
    groupId:  # 知识星球ID
    cookie:  # 知识星球个人cookie信息
    openAiKey: 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 # 自行申请 https://beta.openai.com/overview
    cronExpression: 0/30 * * * * ? # 执行的频次配置，参考：cron.qqe2.com
    silenced: true
